# Generated by Django 3.2.6 on 2021-09-02 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210902_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 2, 18, 30, 41, 912820)),
        ),
    ]
