# Generated by Django 3.2.6 on 2021-09-02 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 2, 16, 58, 42, 889777)),
        ),
    ]
