# Generated by Django 3.2.6 on 2021-09-02 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_story_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 2, 19, 47, 19, 144468)),
        ),
    ]
